[package]
name = "portal-service"
version = "0.1.0"
edition = "2021"
authors = ["Lahcène Belhadi <lahcene.belhadi@gmail.com>"]

# HTTP
# https://crates.io/crates/actix-web
[dependencies.actix-web]
version = "4.3"
