version: "3.9"
services:
  database:
    image: "dbz-portal-service-db"
    volumes:
      - "dbz-portal-database-volume:/var/lib/postgresql/data"
    ports:
      - "5433:5433"

  portal_service:
    image: "dbz-portal-service"
    depends_on:
      - database

volumes:
  dbz-portal-database-volume:

